apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: angrygoose/clients
          context: clients
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.js'
                  dest: .
        - image: angrygoose/comments
          context: comments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: angrygoose/event-bus
          context: event-bus
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: angrygoose/moderation
          context: moderation
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: angrygoose/posts
          context: posts
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: ' *.js'
                  dest: .
        - image: angrygoose/query
          context: query
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .